### PR TITLE
Added option to choose mapping behaviour of entity collection properties

### PR DESCRIPTION
**Pull request by MichaelM223**
Implemented configurable (optional and defaults to true so non-breaking) option to change null value entity collection mapping.
See discussion #82 

Not really satisfied about the option naming but also can't think of something else, suggestions are welcome.

### CODE REVIEW

**Comment by leonardoporro** [comment]
What about NullCollectionBehavior { Set, Ignore } or something like that?

**Comment by MichaelM223** [comment]
Sounds good, will make a commit tonight

**Comment by MichaelM223** [comment]
Changed the name a bit so it is clear it is an option for the EntityCollection type mapper

**Comment by MichaelM223** [comment]
Added unittest for new behaviour option as well

**Comment by MichaelM223** [comment]
Should I resolve the conflicts or will/can you merge them yourself?

**Comment by leonardoporro** [comment]
Instead of adding it to MapperOptions, woudln't be better to add it to MapParameters?
[https://github.com/leonardoporro/Detached-Mapper/blob/main/src/Detached.Mappers/MapParameters.cs](https://github.com/leonardoporro/Detached-Mapper/blob/main/src/Detached.Mappers/MapParameters.cs)

MapperOptions options are for app lifetime, and MapParameters for the scope of the mapping operation.
Is ignoring nulls for all references all the time a valid scenario? or is it better to have it on a per-operation basis?

**Pull request closed without merging**
