### PR TITLE
Added test to demonstrate issue 97

### PR DESCRIPTION
**Pull request by Jogai**
Preliminary PR to demonstrate issue #97.  Maybe wait with merging until there is a fix. I'm happy to help, but I need some directions. Also, I don't know what you think about the other changes. Worst case, you cherry pick what you like.

### CODE REVIEW

**Comment by Jogai** [comment]
@leonardoporro any chance you've got time in the near future to look at this?

**Comment by leonardoporro** [comment]
Hi @Jogai,
Yes, taking a look now. 
I'm sorry, last month I got caught by so many important tasks.
And the only time I had for the library was used to fix a multi-db context issue and improve a bit the initialization.

**Comment by Jogai** [comment]
Awesome. Don't be sorry, I know. Its just that I didnt know where to look, so I wanted to know before I dug in myself.

I rebased to get rid of the conflicts. I'm on linux with only dotnet7 available, so I had to change some extra bits, but just take what you need.

**Comment by Jogai** [comment]
Digging into it, it seems to me its going wrong in the [batchexecutor of efcore](https://github.com/dotnet/efcore/blob/release/7.0/src/EFCore.Relational/Update/Internal/BatchExecutor.cs). Maybe more info tonight.

**Comment by Jogai** [comment]
What I see is 2 entities that are correctly detected as new (those id's are made up by EF is my guess):  
image
First insert is correct (does not use id):
image
But then the next insert fails because the negative id is used, instead of the id that should've returned from the first insert:
image

Error is of course:

> SQLite Error 19: 'FOREIGN KEY constraint failed'.

**Comment by leonardoporro** [comment]
Added a comment on issue 97

**Comment by leonardoporro** [comment]
merged manually
will probably change UnitTest1 for a better name next time

**Pull request merged**
